AWSTemplateFormatVersion: 2010-09-09

Parameters:
  UserName:
    Description: Enter the name for the IAM user
    Type: String
    Default: 'srebalwda'

Resources:

  RoleForB:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::520101086480:root"
            },
            "Action": "sts:AssumeRole",
            "Condition": {}
        }
    ]
}
      Description: A role for Account B to assume Administrator roles in Account A
      Policies:
        - PolicyDocument: {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
                "ec2:CreateVpc",
                "ec2:CreateSubnet",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateRouteTable",
                "ec2:CreateRoute",
                "ec2:CreateInternetGateway",
                "ec2:AttachInternetGateway",
                "ec2:AssociateRouteTable",
                "ec2:ModifyVpcAttribute",
                "ec2:DeleteRouteTable",
                "ec2:CreateRoute",
                "ec2:ReplaceRoute",
                "ec2:DeleteRoute",
                "ec2:DeleteVpc",
                "ec2:DeleteSubnet",
                "ec2:DeleteInternetGateway",
            ],
      "Resource": "*"
    },
    {
      "Action": "ec2:Describe*",
      "Resource": "*",
      "Effect": "Allow"
    }
  ]
}
          PolicyName: PolicyforAwithinB
      RoleName: RoleVPCAccessOfBbyA

  UserinB:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: Azerbaijan@123
        PasswordResetRequired: False
      UserName: !Ref UserName
      Policies:
        - PolicyDocument: {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "ec2:*",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
          PolicyName: EC2FullAccessPolicy

  AdmininB:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: Azerbaijan@123
        PasswordResetRequired: False
      UserName: SREAdminAB
      Policies:
        - PolicyDocument: {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::520101086480:role/RoleAdminAccessOfAbyB"
        }
    ]
}
          PolicyName: AssumeRoleinA
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess