AWSTemplateFormatVersion: 2010-09-09

Parameters:
  UserName:
    Description: Enter the name for the IAM user
    Type: String
    Default: 'occult'

Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: Somalia@123
        PasswordResetRequired: False
      UserName: !Ref UserName
  MyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument: {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateVpc",
                "ec2:CreateSubnet",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateRouteTable",
                "ec2:CreateRoute",
                "ec2:CreateInternetGateway",
                "ec2:AttachInternetGateway",
                "ec2:AssociateRouteTable",
                "ec2:ModifyVpcAttribute",
                "ec2:DeleteRouteTable",
                "ec2:CreateRoute",
                "ec2:ReplaceRoute",
                "ec2:DeleteRoute",
                "ec2:DeleteVpc",
                "ec2:DeleteSubnet",
                "ec2:DeleteInternetGateway"
            ],
            "Resource": "*"
        }
    ]
}
      PolicyName: PolicyForAdarsh
      Users:
        - !Ref MyUser

  SREGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: SREGroup
      
  GroupUser:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref SREGroup
      Users: 
        - !Ref MyUser